### ISSUE TITLE
Plan NACIS 2064 for Mars

### ISSUE THREAD

**Issue by pinakographos** [pinakographos/GithubForNACIS#1]
I think somewhere in the Tharsis Montes would be pretty nice. We should scout for hotels.

**Comment by asteingisser** [comment]
I hear there's water on Mars now but I suspect the coffee price per gallon will be enormous!

**Comment by pinakographos** [comment]
Mars with water.

![mars](https://cloud.githubusercontent.com/assets/5448396/10717371/df15ec0c-7b23-11e5-9675-ea34a4bf99f0.jpeg)
